### ISSUE TITLE
baremetal <-> machine <-> node association missing

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#101]
Right now we don't have any link script like https://github.com/openshift-metal3/dev-scripts/blob/master/link-machine-and-node.sh

I'm opening this issue to track this as otherwise the maintenance mode, etc. won't work.

**Comment by sreichar** [comment]
Any objection to me duplicating that script and add-machine_ips then calling it from 99-post-install?

**Comment by rlopez133** [comment]
#14

**Comment by e-minguez** [comment]
Closed via #110
