### ISSUE TITLE
Once the output of preflight is displayed, get a user confirmation 

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/install-scripts#107]
@schmaustech - once the output is successful, we should still have the user confirm that those values are indeed what they are expecting to use. Could you add a user input that  asks the user if they wish to continue.

**Comment by schmaustech** [comment]
Can you clarify what the flow will look like if the output is not what they are expecting?   That is for preflight since its just discovery and cannot change anything I am trying to understand why we need a confirmation?

**Comment by sreichar** [comment]
After chatting with @schmaustech think this is something we want to do outside ot preflight (just after)
so that  automation can run.   
I will make a small confirmation script and put in the appliance flow.
