### ISSUE TITLE
preflight includes references to ns1 DNS record

### ISSUE THREAD

**Issue by mcornea** [openshift-kni/install-scripts#118]
According to [1] we switched to defining the DNS VIP based on the user input and not from the ns1 DNS record value. 

Currently in install-scripts the DNS VIP is determined based on the ns1 record value [2] which makes the ns1 DNS record a requirement, opposed to dev-scripts where it is not.

Can we clarify if we still want the ns1 DNS record to be a pre-deployment requirement or make it a user input as in dev-scripts?

[1] https://github.com/openshift-metal3/dev-scripts/pull/671
[2] https://github.com/openshift-kni/install-scripts/blob/master/preflight/redfish.yml#L35

**Comment by mcornea** [comment]
From https://github.com/openshift/installer/blob/master/docs/user/metal/install_ipi.md#network-requirements

### Network Requirements

  * ***Reserved VIPs (Virtual IPs)*** - 3 IP addresses must be reserved on this
    network for use by the cluster.  Specifically, these IPs will serve the
    following purposes:
    * API - This IP will be used to reach the cluster API.
    * Ingress - This IP will be used by cluster ingress traffic
    * DNS - This IP will be used internally by the cluster for automating
      internal DNS requirements.
  * ***External DNS*** - While the cluster automates the internal DNS
    requirements, two external DNS records must be created in whatever DNS
    server is appropriate for this environment.
    * `api.<cluster-name>.<base-domain>` - pointing to the API VIP
    * `*.apps.<cluster-name>.<base-domain>` - pointing to the Ingress VIP

**Comment by sreichar** [comment]
@mcornea  - one of the differences between the appliance and generic metal3

From: https://docs.google.com/document/d/1jf2gwt9lVMOnqvSbDHpKhAv4kuO4bzpK3f4YD_l93UQ/edit?usp=sharing


Element | Type | Purpose
-- | -- | --
master-0.<cluster name>.<base domain> | DHCP /  DNS* | Host
master-1.<cluster name>.<base domain> | DHCP /  DNS* | Host
master-2.<cluster name>.<base domain> | DHCP /  DNS* | Host
worker-0.<cluster name>.<base domain> | DHCP /  DNS* | Host
ns1.<cluster name>.<base domain> | DNS | VIP for internal DNS
api.<cluster name>.<base domain> | DNS | VIP for API
*.apps.<cluster name>.<base domain> | Wildcard DNS | VIP for Ingress LB

* - Not strictly required, but recommended

**Comment by mcornea** [comment]
Great, so I guess we can close this one and keep the ns1 record requirement for appliance setups. Thanks!
