### ISSUE TITLE
Wrong hardware data in baremetalhosts

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#121]
This won't be included out-of-the-box until 4.3 but in the meantime we need to ship something.

Currently the hardware data is fake. It would be nice if the preflight script can inspect the hardware prior to installing it and when the baremetal <-> machine <-> node happens that data is used instead a fake one.

**Comment by hardys** [comment]
How would the preflight script inspect the hardware?  That runs on the provisioning host, not the masters, right?

**Comment by e-minguez** [comment]
> How would the preflight script inspect the hardware? That runs on the provisioning host, not the masters, right?

IIRC the preflight script gathers the hosts MAC addresses via redfish [here](https://github.com/openshift-kni/install-scripts/blob/master/preflight/redfish.yml) so maybe it can gather some more information via redfish as well (https://github.com/dell/iDRAC-Redfish-Scripting/tree/master/Redfish%20Python ?) I'm not a redfish expert so I don't know if that would be feasible but just in case.

**Comment by hardys** [comment]
Another option would be to figure it out post-install from the ARP entries, e.g:

```
$ oc describe node master-0 | grep Internal
  InternalIP:  192.168.111.20
$ arp -a | grep "192.168.111.20"
? (192.168.111.20) at 00:79:bf:cb:88:58 [ether] on baremetal
```

**Comment by e-minguez** [comment]
It seems with ansible is pretty straightforward https://docs.ansible.com/ansible/devel/modules/redfish_info_module.html#examples

I've just tested it:

```
ansible localhost -m redfish_facts -a "category=Systems command=GetCpuInventory baseuri=a.b.c.d username=root password=xxx"
localhost | SUCCESS => {
    "ansible_facts": {
        "redfish_facts": {
            "cpu": {
                "entries": [
                    [
                        {
                            "systems_uri": "/redfish/v1/Systems/System.Embedded.1"
                        },
                        [
                            {
                                "Id": "CPU.Socket.1",
                                "Manufacturer": "Intel",
                                "MaxSpeedMHz": 4000,
                                "Model": "Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz",
                                "Status": {
                                    "Health": "OK",
                                    "State": "Enabled"
                                },
                                "TotalCores": 14,
                                "TotalThreads": 28
                            },
                            {
                                "Id": "CPU.Socket.2",
                                "Manufacturer": "Intel",
                                "MaxSpeedMHz": 4000,
                                "Model": "Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz",
                                "Status": {
                                    "Health": "OK",
                                    "State": "Enabled"
                                },
                                "TotalCores": 14,
                                "TotalThreads": 28
                            }
                        ]
                    ]
                ],
                "ret": true
            }
        }
    },
    "changed": false
}
```

**Comment by schmaustech** [comment]
There is quite a bit of detail we can pull from hardware with RedFish as Edu has demonstrated.

**Comment by e-minguez** [comment]
Related https://github.com/openshift-metal3/dev-scripts/issues/767
