### ISSUE TITLE
MTU for storage VLAN

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#131]
The MTU size for the storage VLAN needs to be set to 9000 IIRC. I believe this should be one of the post-install tasks (as an optional step as for CI maybe it doesn't make sense)

**Comment by hardys** [comment]
Why is this needed?  The provisioning NIC is currently only used by the baremetal-operator pod for pxe provisioning, so I'd be wary of making any changes to the global config which may break that.

**Comment by e-minguez** [comment]
> Why is this needed? The provisioning NIC is currently only used by the baremetal-operator pod for pxe provisioning, so I'd be wary of making any changes to the global config which may break that.

My bad, sorry. I've modified the title and description

**Comment by russellb** [comment]
> Why is this needed? The provisioning NIC is currently only used by the baremetal-operator pod for pxe provisioning, so I'd be wary of making any changes to the global config which may break that.

for the storage VLAN on the same NIC, i presume
