### ISSUE TITLE
Need to find getting the oc binary a home

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/install-scripts#139]
For the appliance, we currently have in the slim ISO using the `wget` command to obtain the oc binary file and install it. Code is very similar to what is found in the `01_install_requirement.sh` . We will need to remove this to stay RCM complicant. Since we won't have the appliance call the `01_install_requirements.sh` where should this block of code reside?

```
oc_version=4.2
oc_tools_dir=$HOME/oc-${oc_version}
oc_tools_local_file=openshift-client-${oc_version}.tar.gz
oc_date=0
if which oc 2>&1 >/dev/null ; then
    oc_date=$(date -d $(oc version -o json  | jq -r '.clientVersion.buildDate') +%s)
fi
if [ ! -f ${oc_tools_dir}/${oc_tools_local_file} ] || [ $oc_date -lt 1559308936 ]; then
  mkdir -p ${oc_tools_dir}
  cd ${oc_tools_dir}
  wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/${oc_version}/linux/oc.tar.gz -O ${oc_tools_local_file}
  tar xvzf ${oc_tools_local_file}
  sudo cp oc /usr/local/bin/
fi
```

**Comment by sreichar** [comment]
If oc is not need prior to OpenShift (prep, preflight, validations) then it make sense to do in OPenShift.

There is already a function in 03_create_cluster that extracts that correct version of the oc command, however a version of the OC command is required to extract.

So I suggest adding it to the 03.   If in the extrat_command function it detects oc is not there, call the logic you have in a function to get a version

**Comment by sreichar** [comment]
@rlopez133 Can this be closed now that you found an RPM?
