### ISSUE TITLE
Include demo assets?

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#17]
I'm opening this issue to discuss if we want to host the demo assets (such as deploy amq, ripsaw, windows vm, etc.) in this repository in a contrib/ or demo/ folder.

**Comment by markmc** [comment]
Initial reaction - let's limit this repo to what we expect to do with every production cluster

So if this is a demo we expect to do on every installation, sure - but I'd instead have it in an "e2e-demo/" dir or similar. A "contrib/" says "dumping ground" to me.

**Comment by russellb** [comment]
Agreed with @markmc's initial reaction.

A new repo under openshift-kni could work, too.

**Comment by karmab** [comment]
let's use a new repo under openshift-kni then

**Comment by russellb** [comment]
OK - I'd propose staging the repo somewhere, link it from here so we can review/discuss and then when ready, we can transfer ownership of the repo to openshift-kni.
