### ISSUE TITLE
Feedback on "What's going on here?"

### ISSUE THREAD

**Issue by sreichar** [openshift-kni/install-scripts#26]
"7. Complete some post-install configuration - including machine/node linkage (#14), and configuring a storage VLAN on the provisioning interface on the OpenShift nodes (#4)."
 
"9. Deploy CNV. Configure a bridge on the baremetal interface on OpenShift nodes (#18) to allow VMs access this network.:

 
CAn we please use internal and external to refer to the nics.    The storage VLAN will be configured on the internal interface on the OpehShift Nodes.  While the deployment host will have provisioning and baremetal bridges, these enties do not exist on the OpenShift nodes.

"The cluster name and the domain name under which it will be available.
The network CIDR in which the machines will be allocated IPs on the baremetal network interface.
The 3 IP addresses reserved for API, Ingress, and DNS access.
The BMC IPMI addresses and credentials for the 3 control plane machines."

The cluster name and domain name will be discoverable on the deploy host.
Why do we care what the CIDR is?  Customer is setting up DHCP for external network.
IP are all discoverable from DNS if customer setup is valid.
All 4 IPMI address are hardcoded.

"Optionally, a Network Time Protocol (NTP) server where the default public server is not accessible"
If the customer is not supply NTP option with their DHCP, we would like to have the DHCP for the storage use the switch for NTP/Chronyd.

"To install some required packages and the oc client:

make requirements:"

"To configure libvirt, and prepare the provisioning and baremetal bridges:

make configure"

We want all requirements preinstalled. and the bridges will be configred durinthe iso install.

**Comment by russellb** [comment]
Can you submit a PR with your suggestions?

**Comment by russellb** [comment]
@sreichar ping, in case you missed my last comment.
