### ISSUE TITLE
Enable VLAN filtering on the default network bridge

### ISSUE THREAD

**Issue by phoracek** [openshift-kni/install-scripts#31]
In order to allow pods and VMs connected to the default network bridge to be isolated via VLANs, we should enable vlan_filtering on the bridge and trunk on its uplink port.

https://github.com/openshift-kni/install-scripts/pull/28#issuecomment-521212750

**Comment by e-minguez** [comment]
Can we close this @phoracek ?

**Comment by phoracek** [comment]
Oh yes! Thanks @e-minguez.

Resolved via #47.
