### ISSUE TITLE
Question regarding 02_configure_host.sh

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/install-scripts#37]
Hey @markmc @russellb - I just wanted to confirm, regarding the firewall ports is that something that is required? I see a few ports being opened in 02_configure_host.sh on dev-scripts but I don't see it in install-scripts. I just wanted to confirm whether or not the ports are needed.

- Roger

**Comment by russellb** [comment]
That is correct.  Those were either related to ironic running on the provisioning host, or some dev env specific things (an image cache).
