### ISSUE TITLE
Running `make clean` makes your host unreachable

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#52]
```
$ make clean
...
+ virsh net-uuid baremetal
+ virsh net-destroy baremetal
Network baremetal destroyed

+ virsh net-undefine baremetal
Network baremetal has been undefined

+ sudo ifdown baremetal
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
```

As it just removes the interfaces, the network connection is lost and I cannot connect back to the host.

**Comment by e-minguez** [comment]
It happened to me again. This time I was using the ISO:

```
++ [[ rhel != \r\h\e\l ]]
++ [[ 8 -ne 8 ]]
++ '[' 4085 = 0 ']'
+ virsh net-uuid baremetal
+ virsh net-destroy baremetal
setlocale: No such file or directory
Network baremetal destroyed

+ virsh net-undefine baremetal
setlocale: No such file or directory
Network baremetal has been undefined

+ sudo ifdown baremetal
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
```

**Comment by e-minguez** [comment]
I think this is because in the `dev-scripts` it removes the interfaces depending on the MANAGE_BR_BRIDGE and MANAGE_PRO_BRIDGE (https://github.com/openshift-metal3/dev-scripts/blob/master/host_cleanup.sh#L26-L37) but here it is done no matter what https://github.com/openshift-kni/install-scripts/blob/master/OpenShift/host_cleanup.sh#L12-L14 https://github.com/openshift-kni/install-scripts/blob/master/OpenShift/host_cleanup.sh#L21-L23 but it seems it shouldn't do it based on the `MANAGE_BR_BRIDGE=N` parameter that is hardcoded here https://github.com/schmaustech/preflight/blob/master/config_user.j2#L13

**Comment by sreichar** [comment]
Looking,  at this point I don't see much use of make clean.

I think the only thing that currently make sense is clean the ocp sub-directory?

**Comment by hardys** [comment]
> Looking, at this point I don't see much use of make clean.
> 
> I think the only thing that currently make sense is clean the ocp sub-directory?

I don't see anything that runs openshift-install destroy cluster, so what cleans up the bootstrap VM in the case of a failed deployment?

Note however that we don't have any support in destroy cluster yet for dealing with the baremetal machines, ref https://github.com/openshift/installer/issues/2005 - I'm not yet sure if that will get done in the 4.3 timeframe, so having some docs or scripted workarounds may be helpful (e.g to at least shut down all existing machines before trying to redeploy)

**Comment by sreichar** [comment]
@e-minguez have you given this a try?

I would think depending on this result it would change you PR #65  also could address what you mention in issue #71

**Comment by e-minguez** [comment]
Let me try to create a PR with some more cleaning stuff.
