### ISSUE TITLE
Missing internal registry configuration

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#58]
In order to deploy CNV 2.1 it is required to have access to an internal registry. This can be done via the post-install script but I'm opening this issue to discuss if we want to expose the internal registry hostname in this repo or if we want to have a placeholder and `sed` it while deploying it.
Also, what will happen when we deploy CNV 2.1 on customer basis during the HTB?

**Comment by karmab** [comment]
the idea is that for htb, the content will be available without needing an internal registry
in the mean time, we should use an environment variable to hold the internal registry and create a mco out of it in our post install script

**Comment by e-minguez** [comment]
This #59 is intended to fix this
