### ISSUE TITLE
issues when deploying cnv2.1

### ISSUE THREAD

**Issue by karmab** [openshift-kni/install-scripts#62]
after deploying cnv2.1 i found the two following issues:

-  cdi components are missing (although the operator is there)
- i get an error when trying to create a vm: admission plugin \"MutatingAdmissionWebhook\" failed to complete mutation in 13s

**Comment by karmab** [comment]
@rthallisey ^

**Comment by karmab** [comment]
after rebooting the nodes, cdi components appear and i could successfully launch a vm
i still feel the mutationadmission webhook appeared once i deployed cnv.

**Comment by fabiand** [comment]
@karmab can you please provide some more logs which tell whihc webhhok is malfunctioning?

**Comment by karmab** [comment]
sadly i redeployed. will gather relevant logs when it happens again

**Comment by rthallisey** [comment]
@karmab CDI doesn't currently support the upgrade path from 2.0 to 2.1.  CDI upgrade will be in z-streams.

@mhenriks

**Comment by fabiand** [comment]
@slintes @stu-gott FYI maybe one of the kubevirt webhooks

**Comment by rthallisey** [comment]
Had the wrong context, I thought you were upgrading.  @karmab open a bug against cdi.
