### ISSUE TITLE
Download rhcos and ironic python agent images on provision host first

### ISSUE THREAD

**Issue by mcornea** [openshift-kni/install-scripts#67]
Currently the rhcos and ironic python agent images are downloaded twice from the Internet: first on the bootstrap VM and second on the master node where the metal3 pod is running. The images are ~2G in size so depending on the link parameters to the servers where the images are hosted it may take good minutes for the download to complete(on my test environment it took ~15 minutes to download them once).

In order to save the time it takes to download the images for the 2nd time we could download them once on the provision host and make them available from there.

**Comment by hardys** [comment]
I think we'll have to solve https://github.com/openshift-kni/install-scripts/issues/30 first, e.g we need to extract the version that should be downloaded from the release, which can then be used to generate the ConfigMap for the MAO and used to download a cached version of the image (same as we do in dev-scripts now)

**Comment by mcornea** [comment]
In case of timeout failures caused by coreos-downloader container not downloading the image in time on the bootstrap VM the following manual steps could be done on the provisioning host to create the cache by using dev-scripts

```
sudo dnf install -y podman
git clone https://github.com/openshift-metal3/dev-scripts.git
pushd dev-scripts/
export CONFIG=~/install-scripts/OpenShift/config_$USER.sh
export OPENSHIFT_INSTALLER=~/install-scripts/OpenShift/ocp/openshift-baremetal-install
./04_setup_ironic.sh
```

**Comment by mcornea** [comment]
Looking into the metal3-ipa-downloader container I see ironic-python-agent-latest.tar gets shipped inside the image so we probably need the cache only for the rhcos image:

```shell
[root@rhhi-node-master-0 core]# crictl ps -a | grep ipa
d2f705bf05dbc       quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4fa46488fd3211b7e55fd179edb4c61b78662f96898b12c0e04bcea5c6c710d3   About an hour ago   Exited              metal3-ipa-downloader                    0                   85d4f0e274d90
[root@rhhi-node-master-0 core]# crictl logs d2f705bf05dbc
+ SNAP=current-tripleo-rdo
+ FILENAME=ironic-python-agent
+ FILENAME_EXT=.tar
+ FFILENAME=ironic-python-agent.tar
+ mkdir -p /shared/html/images /shared/tmp
+ cd /shared/html/images
++ mktemp -d -p /shared/tmp
+ TMPDIR=/shared/tmp/tmp.uJJ0kzWxfx
+ '[' -e /usr/share/rhosp-director-images/ironic-python-agent-latest.tar ']'
++ cat /usr/share/rhosp-director-images/version-latest.txt
+ VERSION=15.0,20190715.2.el8ost
+ '[' '!' -e ironic-python-agent-15.0,20190715.2.el8ost ']'
+ cd /shared/tmp/tmp.uJJ0kzWxfx
+ tar -xf /usr/share/rhosp-director-images/ironic-python-agent-latest.tar
+ chmod 755 /shared/tmp/tmp.uJJ0kzWxfx
+ cd -
/shared/html/images
+ mv /shared/tmp/tmp.uJJ0kzWxfx ironic-python-agent-15.0,20190715.2.el8ost
+ ln -sf ironic-python-agent-15.0,20190715.2.el8ost/ironic-python-agent.initramfs ironic-python-agent.initramfs
+ ln -sf ironic-python-agent-15.0,20190715.2.el8ost/ironic-python-agent.kernel ironic-python-agent.kernel
+ exit 0

```

**Comment by hardys** [comment]
> Looking into the metal3-ipa-downloader container I see ironic-python-agent-latest.tar gets shipped inside the image so we probably need the cache only for the rhcos image:

Yes we forgot to remove that when moving to the ART builds, it can probably be removed (or at least made optional) from dev-scripts.

**Comment by e-minguez** [comment]
> In case of timeout failures caused by coreos-downloader container not downloading the image in time on the bootstrap VM the following manual steps could be done on the provisioning host to create the cache by using dev-scripts
> 
> ```
> sudo dnf install -y podman
> git clone https://github.com/openshift-metal3/dev-scripts.git
> pushd dev-scripts/
> export CONFIG=~/install-scripts/OpenShift/config_$USER.sh
> export OPENSHIFT_INSTALLER=~/install-scripts/OpenShift/ocp/openshift-baremetal-install
> ./04_setup_ironic.sh
> ```

I've also needed to do this using the ISO:
```
# Add firewall rules to ensure the image cache can be reached on the host
echo "ZONE=libvirt" | sudo tee -a /etc/sysconfig/network-scripts/ifcfg-provisioning
sudo ifdown provisioning && sudo ifup provisioning
sudo firewall-cmd --zone=libvirt --add-port=80/tcp
sudo firewall-cmd --zone=libvirt --add-port=80/tcp --permanent
```

**Comment by johnbieren** [comment]
Hitting this pretty consistently when trying to use the make targets in a virt environment to have reliable CI for this repo
