### ISSUE TITLE
Deploy OCS

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#7]
Currently there is no deployment method for OCS.

**Comment by russellb** [comment]
related PR: https://github.com/openshift-kni/install-scripts/pull/10/files

**Comment by markmc** [comment]
openshift-kni/install-scripts#10 has merged as a starting point - but this does not deploy OCS itself

**Comment by johnbieren** [comment]
There are also some docs on deploying OCS via OLM here https://github.com/openshift/ocs-operator#install
