### ISSUE TITLE
make CNV and make OCS trigger OpenShift installation

### ISSUE THREAD

**Issue by mcornea** [openshift-kni/install-scripts#81]
The root Makefile includes the OpenShift target as default so when running make CNV or make OCS(after OpenShift was deployed) the installation of a second OpenShift cluster is triggered. 

I'd expect that we can run make CNV/OCS on top of a cluster which was deployed with make OpenShift.

**Comment by sreichar** [comment]
While I don't disagree with you comment, when i did it was thinking we need a cluster to install either OCS or CNV.  However, since it really doesn't not check if the cluster exists, it make sense to remove the dependencies.

Will do, but after #79 merges
