### ISSUE TITLE
Need a way to specify OCS version to deploy

### ISSUE THREAD

**Issue by yprokule** [openshift-kni/install-scripts#84]
To specify which version of OCP to deaploy we use `OPENSHIFT_RELEASE_IMAGE`
vairable, so we need a smth similar to be able to specify version of OCS to deploy.

That's needed to test updates/upgrades.

**Comment by karmab** [comment]
there is a ocs_version environment variable, which is set to release-4.2 
we then deploy ocs with the following line:

```
oc create -f https://raw.githubusercontent.com/openshift/ocs-operator/${ocs_version}/deploy/deploy-with-olm.yaml
```

**Comment by johnbieren** [comment]
The goal here is really to specify a certain build of the 4.2 release, not just a certain release. Saying "4.2 is broken" is not good enough, we want to be able to say build X of the 4.2 release broke things, and build X-1 worked

**Comment by yprokule** [comment]
> The goal here is really to specify a certain build of the 4.2 release, not just a certain release. Saying "4.2 is broken" is not good enough, we want to be able to say build X of the 4.2 release broke things, and build X-1 worked

Exactly @johnbieren
