### ISSUE TITLE
Configure authentication for after OCP4 has been deployed

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#9]
Right now only kube-admin user exists. It would be nice to have a backend authenticatoni mechanism ready after OCP4 is installed.

**Comment by e-minguez** [comment]
Such as:

```
user=admin
password=admin
htpasswd=$(printf "$user:$(openssl passwd -apr1 $password)\n")
htpasswd=$(echo $htpasswd | base64)

oc apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: $htpasswd
EOF

# configure HTPasswd IDP
oc apply -f - <<EOF
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpassidp
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
EOF

sleep 20
oc adm policy add-cluster-role-to-user cluster-admin admin
```

**Comment by russellb** [comment]
Is this something that should be in `install-scripts`, or is an environment specific customization that must be considered on a case by case basis?

**Comment by e-minguez** [comment]
I think it would be nice to have this or any other authentication mechanism (this is just an example) configured 'by default' right after the installation instead just the kube-admin, so they can start adding users in order to start exploring the platform.
Maybe instead having it by default, having some `POSTINSTALL.md` notes about how to configure it after the cluster is up & running.

**Comment by russellb** [comment]
I agree that this is an important post-install task, but I was just wondering if we can make any assumption about which auth mechanism is appropriate.  That may differ for different customer environments.  It makes sense to document though as a list of tasks that should be taken into consideration post-install

**Comment by russellb** [comment]
I would definitely check for existing post-install openshift configuration though, this doesn't seem KNI specific

**Comment by markmc** [comment]
Agree this should be an environment-specific post-install step that we should document, preferably by referencing existing OpenShift documentation
