### ISSUE TITLE
baremetalhosts.metal3.io crd shouldn't be needed

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#90]
IIRC, the baremetalhosts.metal3.io crd is included in the MAO (https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_13_baremetalhost.crd.yaml) so it won't be needed to add it at install [time](https://github.com/openshift-kni/install-scripts/blob/master/OpenShift/03_create_cluster.sh#L80-L82), right?

**Comment by hardys** [comment]
I think @dhellmann was looking at removing this from dev-scripts and ran into some issues, so we probably need to confirm it's working in dev-scripts, then remove it from install-scripts
